create table if not exists public.bible_state (
  user_id uuid primary key references auth.users (id) on delete cascade,
  app_theme text not null default 'light',
  app_language text not null default 'ko',
  bible_search_info jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.favorite_verses (
  user_id uuid not null references auth.users (id) on delete cascade,
  book_code text not null,
  chapter integer not null,
  verse integer not null,
  verse_text text not null default '',
  created_at text not null default '',
  primary key (user_id, book_code, chapter, verse)
);

create table if not exists public.memos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  title text not null default '',
  content text not null default '',
  verse_text text not null default '',
  created_at text not null default ''
);

alter table public.memos add column if not exists client_id text;

create index if not exists memos_user_id_created_at_idx
  on public.memos (user_id, created_at desc, id desc);

create unique index if not exists memos_user_id_client_id_idx
  on public.memos (user_id, client_id)
  where client_id is not null;

create table if not exists public.memo_verses (
  user_id uuid not null references auth.users (id) on delete cascade,
  memo_id bigint not null references public.memos (id) on delete cascade,
  book_code text not null,
  chapter integer not null,
  verse integer not null,
  primary key (user_id, memo_id, book_code, chapter, verse)
);

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  plan_name text not null default '',
  plan_description text not null default '',
  start_date text not null default '',
  end_date text not null default '',
  total_read_count integer not null default 0,
  current_read_count integer not null default 0,
  goal_percent double precision not null default 0,
  read_count_per_day double precision not null default 0,
  rest_day integer not null default 0,
  goal_status jsonb not null default '[]'::jsonb,
  selected_book_codes jsonb not null default '[]'::jsonb,
  created_at text not null default '',
  updated_at text not null default ''
);

alter table public.plans add column if not exists client_id text;
alter table public.plans add column if not exists plan_description text not null default '';

create index if not exists plans_user_id_idx
  on public.plans (user_id, id desc);

create unique index if not exists plans_user_id_client_id_idx
  on public.plans (user_id, client_id)
  where client_id is not null;

create table if not exists public.bible_plan_template (
  id bigint generated by default as identity primary key,
  language_code text not null default 'ko',
  template_name text not null default '',
  template_explanation text not null default '',
  selected_book_codes jsonb not null default '[]'::jsonb
);

create index if not exists bible_plan_template_language_code_idx
  on public.bible_plan_template (language_code, id);

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default '',
  email text,
  show_email boolean not null default false,
  avatar_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.user_profiles
  add column if not exists show_email boolean not null default false;

create table if not exists public.churches (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  image_url text,
  shared_plan_ranking_public boolean not null default true,
  shared_plan_progress_public boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  created_by_user_id uuid not null references auth.users (id) on delete restrict,
  super_admin_user_id uuid not null references auth.users (id) on delete restrict,
  member_count integer not null default 0,
  deputy_admin_user_ids text not null default ''
);

create index if not exists churches_name_idx
  on public.churches (name);

alter table public.churches add column if not exists description text not null default '';
alter table public.churches add column if not exists image_url text;
alter table public.churches add column if not exists shared_plan_ranking_public boolean not null default true;
alter table public.churches add column if not exists shared_plan_progress_public boolean not null default true;

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  created_by_user_id uuid not null references auth.users (id) on delete restrict,
  leader_user_id uuid references auth.users (id) on delete set null
);

create unique index if not exists teams_church_id_name_idx
  on public.teams (church_id, name);

create index if not exists teams_church_id_idx
  on public.teams (church_id, id desc);

create table if not exists public.church_memberships (
  church_id bigint not null references public.churches (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  team_id bigint references public.teams (id) on delete set null,
  joined_at timestamptz not null default timezone('utc', now()),
  created_by_user_id uuid references auth.users (id) on delete set null,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (church_id, user_id),
  constraint church_memberships_role_check check (role in ('super_admin', 'deputy_admin', 'member'))
);

create index if not exists church_memberships_user_id_idx
  on public.church_memberships (user_id, joined_at desc);

create index if not exists church_memberships_church_id_team_id_idx
  on public.church_memberships (church_id, team_id);

create table if not exists public.church_join_requests (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches (id) on delete cascade,
  requester_user_id uuid not null references auth.users (id) on delete cascade,
  status text not null default 'pending',
  requested_at timestamptz not null default timezone('utc', now()),
  processed_at timestamptz,
  processed_by_user_id uuid references auth.users (id) on delete set null,
  constraint church_join_requests_status_check check (status in ('pending', 'approved', 'rejected', 'cancelled'))
);

create index if not exists church_join_requests_church_id_status_idx
  on public.church_join_requests (church_id, status, requested_at desc);

create unique index if not exists church_join_requests_pending_unique_idx
  on public.church_join_requests (church_id, requester_user_id)
  where status = 'pending';

alter table public.plans
  add column if not exists church_id bigint references public.churches (id) on delete cascade;

alter table public.plans
  add column if not exists team_id bigint references public.teams (id) on delete cascade;

create index if not exists plans_church_id_idx
  on public.plans (church_id, id desc);

create index if not exists plans_team_id_idx
  on public.plans (team_id, id desc);

create table if not exists public.plan_progresses (
  plan_id bigint not null references public.plans (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  goal_status jsonb not null default '[]'::jsonb,
  current_read_count integer not null default 0,
  goal_percent double precision not null default 0,
  read_count_per_day double precision not null default 0,
  rest_day integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (plan_id, user_id)
);

create index if not exists plan_progresses_user_id_idx
  on public.plan_progresses (user_id, updated_at desc);

create table if not exists public.church_prayers (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches (id) on delete cascade,
  team_id bigint references public.teams (id) on delete cascade,
  requester text not null default '',
  relation varchar(50) not null default '',
  target text not null default '',
  created_by_user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null default '',
  updated_at text not null default ''
);

alter table public.church_prayers
  add column if not exists relation varchar(50) not null default '';

create index if not exists church_prayers_church_id_updated_at_idx
  on public.church_prayers (church_id, updated_at desc, id desc);

create index if not exists church_prayers_team_id_updated_at_idx
  on public.church_prayers (team_id, updated_at desc, id desc);

create table if not exists public.church_prayer_contents (
  id bigint generated by default as identity primary key,
  prayer_id bigint not null references public.church_prayers (id) on delete cascade,
  created_by_user_id uuid not null references auth.users (id) on delete cascade,
  content text not null default '',
  registered_at text not null default ''
);

create index if not exists church_prayer_contents_prayer_id_registered_at_idx
  on public.church_prayer_contents (prayer_id, registered_at desc, id desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function public.is_church_member(p_church_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.church_memberships membership
    where membership.church_id = p_church_id
      and membership.user_id = p_user_id
  );
$$;

create or replace function public.is_church_admin(p_church_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.church_memberships membership
    where membership.church_id = p_church_id
      and membership.user_id = p_user_id
      and membership.role in ('super_admin', 'deputy_admin')
  );
$$;

create or replace function public.is_church_super_admin(p_church_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.church_memberships membership
    where membership.church_id = p_church_id
      and membership.user_id = p_user_id
      and membership.role = 'super_admin'
  );
$$;

create or replace function public.is_plan_target_member(p_plan_id bigint, p_user_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.plans plan
    join public.church_memberships membership
      on membership.church_id = plan.church_id
     and membership.user_id = p_user_id
    where plan.id = p_plan_id
      and plan.church_id is not null
      and (plan.team_id is null or membership.team_id = plan.team_id)
  );
$$;

create or replace function public.can_access_church_audience(
  p_church_id bigint,
  p_team_id bigint,
  p_user_id uuid
)
returns boolean
language sql
security definer
set search_path = public
as $church_prayer_access$
  select exists (
    select 1
    from public.church_memberships membership
    where membership.church_id = p_church_id
      and membership.user_id = p_user_id
      and (
        p_team_id is null
        or membership.team_id = p_team_id
        or membership.role in ('super_admin', 'deputy_admin')
      )
  );
$church_prayer_access$;

create or replace function public.can_access_church_prayer(
  p_prayer_id bigint,
  p_user_id uuid
)
returns boolean
language sql
security definer
set search_path = public
as $church_prayer_read$
  select exists (
    select 1
    from public.church_prayers prayer
    where prayer.id = p_prayer_id
      and public.can_access_church_audience(prayer.church_id, prayer.team_id, p_user_id)
  );
$church_prayer_read$;

create or replace function public.can_manage_church_prayer(
  p_prayer_id bigint,
  p_user_id uuid
)
returns boolean
language sql
security definer
set search_path = public
as $church_prayer_manage$
  select exists (
    select 1
    from public.church_prayers prayer
    where prayer.id = p_prayer_id
      and (
        prayer.created_by_user_id = p_user_id
        or public.is_church_admin(prayer.church_id, p_user_id)
      )
  );
$church_prayer_manage$;

create or replace function public.can_manage_church_prayer_content(
  p_content_id bigint,
  p_user_id uuid
)
returns boolean
language sql
security definer
set search_path = public
as $church_prayer_content_manage$
  select exists (
    select 1
    from public.church_prayer_contents content
    where content.id = p_content_id
      and (
        content.created_by_user_id = p_user_id
        or public.can_manage_church_prayer(content.prayer_id, p_user_id)
      )
  );
$church_prayer_content_manage$;

create or replace function public.can_read_user_profile(
  p_target_user_id uuid,
  p_actor_user_id uuid
)
returns boolean
language sql
security definer
set search_path = public
as $$
  select
    p_actor_user_id is not null
    and (
      p_target_user_id = p_actor_user_id
      or exists (
        select 1
        from public.church_memberships target_membership
        join public.church_memberships actor_membership
          on actor_membership.church_id = target_membership.church_id
         and actor_membership.user_id = p_actor_user_id
        where target_membership.user_id = p_target_user_id
      )
      or exists (
        select 1
        from public.church_join_requests request
        where request.requester_user_id = p_target_user_id
          and public.is_church_admin(request.church_id, p_actor_user_id)
      )
    );
$$;

create or replace function public.get_visible_user_profiles(
  p_user_ids uuid[]
)
returns table (
  user_id uuid,
  display_name text,
  email text,
  show_email boolean,
  avatar_url text
)
language sql
security definer
set search_path = public
as $$
  select
    profile.user_id,
    profile.display_name,
    case
      when profile.user_id = auth.uid() or profile.show_email then profile.email
      else null
    end as email,
    profile.show_email,
    profile.avatar_url
  from public.user_profiles profile
  where profile.user_id = any(coalesce(p_user_ids, array[]::uuid[]))
    and public.can_read_user_profile(profile.user_id, auth.uid());
$$;

create or replace function public.sync_church_cached_fields(p_church_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.churches church
  set member_count = (
        select count(*)
        from public.church_memberships membership
        where membership.church_id = p_church_id
      ),
      deputy_admin_user_ids = coalesce((
        select string_agg(membership.user_id::text, ', ' order by membership.joined_at, membership.user_id::text)
        from public.church_memberships membership
        where membership.church_id = p_church_id
          and membership.role = 'deputy_admin'
      ), ''),
      updated_at = timezone('utc', now())
  where church.id = p_church_id;
end;
$$;

create or replace function public.sync_plan_progress_rows_for_plan(p_plan_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_church_id bigint;
  v_team_id bigint;
begin
  select plan.church_id, plan.team_id
  into v_church_id, v_team_id
  from public.plans plan
  where plan.id = p_plan_id;

  if v_church_id is null then
    return;
  end if;

  insert into public.plan_progresses (
    plan_id,
    user_id,
    goal_status,
    current_read_count,
    goal_percent,
    read_count_per_day,
    rest_day
  )
  select
    p_plan_id,
    membership.user_id,
    '[]'::jsonb,
    0,
    0,
    0,
    0
  from public.church_memberships membership
  where membership.church_id = v_church_id
    and (v_team_id is null or membership.team_id = v_team_id)
  on conflict (plan_id, user_id) do nothing;
end;
$$;

create or replace function public.sync_plan_progress_rows_for_member(
  p_church_id bigint,
  p_user_id uuid,
  p_team_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.plan_progresses (
    plan_id,
    user_id,
    goal_status,
    current_read_count,
    goal_percent,
    read_count_per_day,
    rest_day
  )
  select
    plan.id,
    p_user_id,
    '[]'::jsonb,
    0,
    0,
    0,
    0
  from public.plans plan
  where plan.church_id = p_church_id
    and (plan.team_id is null or plan.team_id = p_team_id)
  on conflict (plan_id, user_id) do nothing;
end;
$$;

create or replace function public.handle_church_membership_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.sync_church_cached_fields(old.church_id);
    return old;
  end if;

  perform public.sync_church_cached_fields(new.church_id);
  perform public.sync_plan_progress_rows_for_member(new.church_id, new.user_id, new.team_id);
  return new;
end;
$$;

create or replace function public.handle_plan_audience_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.church_id is not null then
    perform public.sync_plan_progress_rows_for_plan(new.id);
  end if;

  return new;
end;
$$;

create or replace function public.create_church(
  p_name text,
  p_description text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_name text;
  v_description text;
  v_church_id bigint;
begin
  v_user_id := auth.uid();
  v_name := trim(coalesce(p_name, ''));
  v_description := trim(coalesce(p_description, ''));

  if v_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if v_name = '' then
    raise exception 'CHURCH_NAME_REQUIRED';
  end if;

  insert into public.churches (
    name,
    description,
    created_by_user_id,
    super_admin_user_id
  )
  values (
    v_name,
    v_description,
    v_user_id,
    v_user_id
  )
  returning id into v_church_id;

  insert into public.church_memberships (
    church_id,
    user_id,
    role,
    created_by_user_id
  )
  values (
    v_church_id,
    v_user_id,
    'super_admin',
    v_user_id
  )
  on conflict (church_id, user_id) do nothing;

  perform public.sync_church_cached_fields(v_church_id);

  return v_church_id;
end;
$$;

create or replace function public.create_church(p_name text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
begin
  return public.create_church(p_name, '');
end;
$$;

create or replace function public.update_church_info(
  p_church_id bigint,
  p_name text,
  p_description text,
  p_shared_plan_ranking_public boolean,
  p_shared_plan_progress_public boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid;
  v_name text;
  v_description text;
begin
  v_actor_user_id := auth.uid();
  v_name := trim(coalesce(p_name, ''));
  v_description := trim(coalesce(p_description, ''));

  if v_actor_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if v_name = '' then
    raise exception 'CHURCH_NAME_REQUIRED';
  end if;

  if not public.is_church_super_admin(p_church_id, v_actor_user_id) then
    raise exception 'PERMISSION_DENIED';
  end if;

  update public.churches church
  set name = v_name,
      description = v_description,
      shared_plan_ranking_public = coalesce(p_shared_plan_ranking_public, true),
      shared_plan_progress_public = coalesce(p_shared_plan_progress_public, true)
  where church.id = p_church_id;

  if not found then
    raise exception 'CHURCH_NOT_FOUND';
  end if;
end;
$$;

create or replace function public.update_church_info(
  p_church_id bigint,
  p_name text,
  p_description text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid;
  v_name text;
  v_description text;
begin
  perform public.update_church_info(
    p_church_id,
    p_name,
    p_description,
    coalesce(
      (select church.shared_plan_ranking_public from public.churches church where church.id = p_church_id),
      true
    ),
    coalesce(
      (select church.shared_plan_progress_public from public.churches church where church.id = p_church_id),
      true
    )
  );
end;
$$;

create or replace function public.set_church_image_url(
  p_church_id bigint,
  p_image_url text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid;
begin
  v_actor_user_id := auth.uid();

  if v_actor_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if not public.is_church_admin(p_church_id, v_actor_user_id) then
    raise exception 'PERMISSION_DENIED';
  end if;

  update public.churches church
  set image_url = nullif(trim(coalesce(p_image_url, '')), '')
  where church.id = p_church_id;

  if not found then
    raise exception 'CHURCH_NOT_FOUND';
  end if;
end;
$$;

create or replace function public.set_team_leader(
  p_team_id bigint,
  p_leader_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid;
  v_church_id bigint;
begin
  v_actor_user_id := auth.uid();

  if v_actor_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select team.church_id
  into v_church_id
  from public.teams team
  where team.id = p_team_id;

  if v_church_id is null then
    raise exception 'TEAM_NOT_FOUND';
  end if;

  if not public.is_church_admin(v_church_id, v_actor_user_id) then
    raise exception 'PERMISSION_DENIED';
  end if;

  if p_leader_user_id is not null and not exists (
    select 1
    from public.church_memberships membership
    where membership.church_id = v_church_id
      and membership.user_id = p_leader_user_id
      and membership.team_id = p_team_id
  ) then
    raise exception 'TEAM_LEADER_MUST_BE_TEAM_MEMBER';
  end if;

  update public.teams team
  set leader_user_id = p_leader_user_id
  where team.id = p_team_id;
end;
$$;

create or replace function public.set_church_member_team(
  p_church_id bigint,
  p_target_user_id uuid,
  p_team_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid;
  v_actor_role text;
  v_target_role text;
begin
  v_actor_user_id := auth.uid();

  if v_actor_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select membership.role
  into v_actor_role
  from public.church_memberships membership
  where membership.church_id = p_church_id
    and membership.user_id = v_actor_user_id;

  if v_actor_role is null then
    raise exception 'PERMISSION_DENIED';
  end if;

  select membership.role
  into v_target_role
  from public.church_memberships membership
  where membership.church_id = p_church_id
    and membership.user_id = p_target_user_id;

  if v_target_role is null then
    raise exception 'CHURCH_MEMBER_NOT_FOUND';
  end if;

  if p_team_id is not null and not exists (
    select 1
    from public.teams team
    where team.id = p_team_id
      and team.church_id = p_church_id
  ) then
    raise exception 'TEAM_NOT_FOUND';
  end if;

  if not (
    v_actor_role = 'super_admin'
    or (v_actor_role = 'deputy_admin' and v_target_role = 'member')
  ) then
    raise exception 'PERMISSION_DENIED';
  end if;

  update public.church_memberships membership
  set team_id = p_team_id
  where membership.church_id = p_church_id
    and membership.user_id = p_target_user_id;
end;
$$;

create or replace function public.remove_church_member(
  p_church_id bigint,
  p_target_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid;
  v_actor_role text;
  v_target_role text;
begin
  v_actor_user_id := auth.uid();

  if v_actor_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select membership.role
  into v_actor_role
  from public.church_memberships membership
  where membership.church_id = p_church_id
    and membership.user_id = v_actor_user_id;

  select membership.role
  into v_target_role
  from public.church_memberships membership
  where membership.church_id = p_church_id
    and membership.user_id = p_target_user_id;

  if v_target_role is null then
    raise exception 'CHURCH_MEMBER_NOT_FOUND';
  end if;

  if v_actor_user_id = p_target_user_id then
    if v_target_role = 'super_admin' then
      raise exception 'SUPER_ADMIN_CANNOT_LEAVE';
    end if;
  elsif not (
    v_actor_role = 'super_admin'
    or (v_actor_role = 'deputy_admin' and v_target_role = 'member')
  ) then
    raise exception 'PERMISSION_DENIED';
  elsif v_target_role = 'super_admin' then
    raise exception 'SUPER_ADMIN_CANNOT_BE_REMOVED';
  end if;

  delete from public.church_memberships membership
  where membership.church_id = p_church_id
    and membership.user_id = p_target_user_id;
end;
$$;

create or replace function public.cleanup_team_leader_on_membership_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    update public.teams team
    set leader_user_id = null
    where team.church_id = old.church_id
      and team.leader_user_id = old.user_id;

    return old;
  end if;

  if old.team_id is distinct from new.team_id then
    update public.teams team
    set leader_user_id = null
    where team.church_id = old.church_id
      and team.id = old.team_id
      and team.leader_user_id = old.user_id;
  end if;

  return new;
end;
$$;

create or replace function public.validate_church_prayer_team_scope()
returns trigger
language plpgsql
security definer
set search_path = public
as $church_prayer_validate$
begin
  if new.team_id is not null and not exists (
    select 1
    from public.teams team
    where team.id = new.team_id
      and team.church_id = new.church_id
  ) then
    raise exception 'INVALID_PRAYER_TEAM_SCOPE';
  end if;

  return new;
end;
$church_prayer_validate$;

create or replace function public.sync_church_prayer_updated_at_from_content()
returns trigger
language plpgsql
security definer
set search_path = public
as $church_prayer_touch$
declare
  v_prayer_id bigint;
begin
  v_prayer_id := case when tg_op = 'DELETE' then old.prayer_id else new.prayer_id end;

  update public.church_prayers prayer
  set updated_at = to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS')
  where prayer.id = v_prayer_id;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$church_prayer_touch$;

revoke all on function public.create_church(text) from public;
grant execute on function public.create_church(text) to authenticated;
revoke all on function public.create_church(text, text) from public;
grant execute on function public.create_church(text, text) to authenticated;
revoke all on function public.update_church_info(bigint, text, text) from public;
grant execute on function public.update_church_info(bigint, text, text) to authenticated;
revoke all on function public.update_church_info(bigint, text, text, boolean, boolean) from public;
grant execute on function public.update_church_info(bigint, text, text, boolean, boolean) to authenticated;
revoke all on function public.set_church_image_url(bigint, text) from public;
grant execute on function public.set_church_image_url(bigint, text) to authenticated;
revoke all on function public.set_team_leader(bigint, uuid) from public;
grant execute on function public.set_team_leader(bigint, uuid) to authenticated;
revoke all on function public.set_church_member_team(bigint, uuid, bigint) from public;
grant execute on function public.set_church_member_team(bigint, uuid, bigint) to authenticated;
revoke all on function public.remove_church_member(bigint, uuid) from public;
grant execute on function public.remove_church_member(bigint, uuid) to authenticated;
revoke all on function public.can_read_user_profile(uuid, uuid) from public;
grant execute on function public.can_read_user_profile(uuid, uuid) to authenticated;
revoke all on function public.get_visible_user_profiles(uuid[]) from public;
grant execute on function public.get_visible_user_profiles(uuid[]) to authenticated;

drop trigger if exists user_profiles_set_updated_at on public.user_profiles;
create trigger user_profiles_set_updated_at
before update on public.user_profiles
for each row
execute function public.touch_updated_at();

drop trigger if exists churches_set_updated_at on public.churches;
create trigger churches_set_updated_at
before update on public.churches
for each row
execute function public.touch_updated_at();

drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at
before update on public.teams
for each row
execute function public.touch_updated_at();

drop trigger if exists church_memberships_set_updated_at on public.church_memberships;
create trigger church_memberships_set_updated_at
before update on public.church_memberships
for each row
execute function public.touch_updated_at();

drop trigger if exists church_memberships_cleanup_team_leader on public.church_memberships;
create trigger church_memberships_cleanup_team_leader
after update of team_id or delete on public.church_memberships
for each row
execute function public.cleanup_team_leader_on_membership_change();

drop trigger if exists plan_progresses_set_updated_at on public.plan_progresses;
create trigger plan_progresses_set_updated_at
before update on public.plan_progresses
for each row
execute function public.touch_updated_at();

drop trigger if exists church_prayers_validate_team_scope on public.church_prayers;
create trigger church_prayers_validate_team_scope
before insert or update on public.church_prayers
for each row
execute function public.validate_church_prayer_team_scope();

drop trigger if exists church_prayer_contents_sync_updated_at on public.church_prayer_contents;
create trigger church_prayer_contents_sync_updated_at
after insert or update or delete on public.church_prayer_contents
for each row
execute function public.sync_church_prayer_updated_at_from_content();

drop trigger if exists church_memberships_after_write_sync on public.church_memberships;
create trigger church_memberships_after_write_sync
after insert or update or delete on public.church_memberships
for each row
execute function public.handle_church_membership_change();

drop trigger if exists plans_after_write_sync_progress on public.plans;
create trigger plans_after_write_sync_progress
after insert or update of church_id, team_id on public.plans
for each row
execute function public.handle_plan_audience_change();

create table if not exists public.prayers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  is_my_prayer boolean not null default false,
  requester text not null default '',
  relation varchar(50) not null default '',
  target text not null default '',
  created_at text not null default ''
);

alter table public.prayers
  add column if not exists relation varchar(50) not null default '';

alter table public.prayers add column if not exists client_id text;

alter table public.prayers
  add column if not exists is_my_prayer boolean not null default false;

create unique index if not exists prayers_user_id_client_id_idx
  on public.prayers (user_id, client_id)
  where client_id is not null;

create table if not exists public.prayer_contents (
  id bigint generated by default as identity primary key,
  prayer_id bigint not null references public.prayers (id) on delete cascade,
  client_id text,
  content text not null default '',
  registered_at text not null default ''
);

alter table public.prayer_contents add column if not exists client_id text;

drop index if exists public.prayer_contents_user_id_prayer_id_idx;
drop index if exists public.prayer_contents_user_id_client_id_idx;

create index if not exists prayer_contents_prayer_id_registered_at_idx
  on public.prayer_contents (prayer_id, registered_at desc, id desc);

create unique index if not exists prayer_contents_prayer_id_client_id_idx
  on public.prayer_contents (prayer_id, client_id)
  where client_id is not null;

create table if not exists public.bible_grass (
  user_id uuid not null references auth.users (id) on delete cascade,
  date text not null,
  data jsonb not null default '[]'::jsonb,
  primary key (user_id, date)
);

create table if not exists public.theme_verses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  year integer not null,
  book_code text not null default '',
  chapter integer not null default 1,
  verse integer not null default 1,
  verse_numbers jsonb not null default '[]'::jsonb,
  verse_text text not null default '',
  description text not null default '',
  created_at text not null default '',
  updated_at text not null default ''
);

create unique index if not exists theme_verses_user_id_year_idx
  on public.theme_verses (user_id, year);

create unique index if not exists theme_verses_user_id_client_id_idx
  on public.theme_verses (user_id, client_id)
  where client_id is not null;

create table if not exists public.developer_inquiries (
  id bigint generated by default as identity primary key,
  author_user_id uuid references auth.users (id) on delete set null,
  author_name text not null default '',
  title text not null default '',
  content text not null default '',
  answer_content text not null default '',
  status text not null default 'inquiry',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint developer_inquiries_status_check check (status in ('inquiry', 'answered'))
);

create index if not exists developer_inquiries_status_created_at_idx
  on public.developer_inquiries (status, created_at desc, id desc);

create index if not exists developer_inquiries_author_user_id_created_at_idx
  on public.developer_inquiries (author_user_id, created_at desc, id desc);

drop trigger if exists developer_inquiries_set_updated_at on public.developer_inquiries;
create trigger developer_inquiries_set_updated_at
before update on public.developer_inquiries
for each row
execute function public.touch_updated_at();

create table if not exists public.image_infos (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  original_name text not null default '',
  stored_name text not null default '',
  object_key text not null,
  file_extension text not null default '',
  mime_type text not null default '',
  file_size_bytes bigint not null default 0,
  bucket_name text not null default '',
  region text not null default '',
  url text not null default '',
  etag text,
  uploaded_at timestamptz not null default timezone('utc', now()),
  constraint image_infos_file_size_bytes_check check (file_size_bytes >= 0)
);

create index if not exists image_infos_user_id_uploaded_at_idx
  on public.image_infos (user_id, uploaded_at desc, id desc);

create unique index if not exists image_infos_object_key_idx
  on public.image_infos (object_key);

alter table public.bible_state enable row level security;
alter table public.favorite_verses enable row level security;
alter table public.memos enable row level security;
alter table public.memo_verses enable row level security;
alter table public.plans enable row level security;
alter table public.bible_plan_template enable row level security;
alter table public.user_profiles enable row level security;
alter table public.churches enable row level security;
alter table public.teams enable row level security;
alter table public.church_memberships enable row level security;
alter table public.church_join_requests enable row level security;
alter table public.plan_progresses enable row level security;
alter table public.church_prayers enable row level security;
alter table public.church_prayer_contents enable row level security;
alter table public.prayers enable row level security;
alter table public.prayer_contents enable row level security;
alter table public.bible_grass enable row level security;
alter table public.theme_verses enable row level security;
alter table public.developer_inquiries enable row level security;
alter table public.image_infos enable row level security;

drop policy if exists "bible_state_owner" on public.bible_state;
create policy "bible_state_owner"
  on public.bible_state
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "favorite_verses_owner" on public.favorite_verses;
create policy "favorite_verses_owner"
  on public.favorite_verses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "memos_owner" on public.memos;
create policy "memos_owner"
  on public.memos
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "memo_verses_owner" on public.memo_verses;
create policy "memo_verses_owner"
  on public.memo_verses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "plans_owner" on public.plans;
drop policy if exists "plans_select_access" on public.plans;
drop policy if exists "plans_insert_access" on public.plans;
drop policy if exists "plans_update_access" on public.plans;
drop policy if exists "plans_delete_access" on public.plans;
create policy "plans_select_access"
  on public.plans
  for select
  using (
    auth.uid() = user_id
    or (
      church_id is not null
      and public.is_church_member(church_id, auth.uid())
    )
  );
create policy "plans_insert_access"
  on public.plans
  for insert
  with check (
    auth.uid() = user_id
    and (
      (church_id is null and team_id is null)
      or (
        church_id is not null
        and (
          public.is_church_super_admin(church_id, auth.uid())
          or (team_id is not null and public.is_church_admin(church_id, auth.uid()))
        )
      )
    )
  );
create policy "plans_update_access"
  on public.plans
  for update
  using (
    (church_id is null and auth.uid() = user_id)
    or (
      church_id is not null
      and (
        public.is_church_super_admin(church_id, auth.uid())
        or (team_id is not null and public.is_church_admin(church_id, auth.uid()))
      )
    )
  )
  with check (
    (church_id is null and auth.uid() = user_id)
    or (
      church_id is not null
      and (
        public.is_church_super_admin(church_id, auth.uid())
        or (team_id is not null and public.is_church_admin(church_id, auth.uid()))
      )
    )
  );
create policy "plans_delete_access"
  on public.plans
  for delete
  using (
    (church_id is null and auth.uid() = user_id)
    or (
      church_id is not null
      and (
        public.is_church_super_admin(church_id, auth.uid())
        or (team_id is not null and public.is_church_admin(church_id, auth.uid()))
      )
    )
  );

drop policy if exists "bible_plan_template_read_public" on public.bible_plan_template;
create policy "bible_plan_template_read_public"
  on public.bible_plan_template
  for select
  using (true);

drop policy if exists "user_profiles_read_authenticated" on public.user_profiles;
drop policy if exists "user_profiles_read_same_church_or_self" on public.user_profiles;
drop policy if exists "user_profiles_read_self" on public.user_profiles;
drop policy if exists "user_profiles_self_insert" on public.user_profiles;
drop policy if exists "user_profiles_self_update" on public.user_profiles;
drop policy if exists "user_profiles_self_delete" on public.user_profiles;
create policy "user_profiles_read_self"
  on public.user_profiles
  for select
  using (auth.uid() = user_id);
create policy "user_profiles_self_insert"
  on public.user_profiles
  for insert
  with check (auth.uid() = user_id);
create policy "user_profiles_self_update"
  on public.user_profiles
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
create policy "user_profiles_self_delete"
  on public.user_profiles
  for delete
  using (auth.uid() = user_id);

drop policy if exists "churches_read_authenticated" on public.churches;
drop policy if exists "churches_update_super_admin" on public.churches;
drop policy if exists "churches_update_admins" on public.churches;
create policy "churches_read_authenticated"
  on public.churches
  for select
  using (auth.role() = 'authenticated');
create policy "churches_update_admins"
  on public.churches
  for update
  using (public.is_church_admin(id, auth.uid()))
  with check (public.is_church_admin(id, auth.uid()));

drop policy if exists "teams_read_members" on public.teams;
drop policy if exists "teams_manage_admins" on public.teams;
create policy "teams_read_members"
  on public.teams
  for select
  using (public.is_church_member(church_id, auth.uid()));
create policy "teams_manage_admins"
  on public.teams
  for all
  using (public.is_church_admin(church_id, auth.uid()))
  with check (public.is_church_admin(church_id, auth.uid()));

drop policy if exists "church_memberships_read_members" on public.church_memberships;
drop policy if exists "church_memberships_insert_admins" on public.church_memberships;
drop policy if exists "church_memberships_update_super_admin" on public.church_memberships;
drop policy if exists "church_memberships_delete_super_admin" on public.church_memberships;
create policy "church_memberships_read_members"
  on public.church_memberships
  for select
  using (
    auth.uid() = user_id
    or public.is_church_member(church_id, auth.uid())
  );
create policy "church_memberships_insert_admins"
  on public.church_memberships
  for insert
  with check (
    public.is_church_admin(church_id, auth.uid())
    and auth.uid() = created_by_user_id
  );
create policy "church_memberships_update_super_admin"
  on public.church_memberships
  for update
  using (public.is_church_super_admin(church_id, auth.uid()))
  with check (public.is_church_super_admin(church_id, auth.uid()));
create policy "church_memberships_delete_super_admin"
  on public.church_memberships
  for delete
  using (public.is_church_super_admin(church_id, auth.uid()));

drop policy if exists "church_join_requests_select_access" on public.church_join_requests;
drop policy if exists "church_join_requests_insert_self" on public.church_join_requests;
drop policy if exists "church_join_requests_update_admins" on public.church_join_requests;
create policy "church_join_requests_select_access"
  on public.church_join_requests
  for select
  using (
    requester_user_id = auth.uid()
    or public.is_church_admin(church_id, auth.uid())
  );
create policy "church_join_requests_insert_self"
  on public.church_join_requests
  for insert
  with check (
    requester_user_id = auth.uid()
    and auth.role() = 'authenticated'
  );
create policy "church_join_requests_update_admins"
  on public.church_join_requests
  for update
  using (public.is_church_admin(church_id, auth.uid()))
  with check (public.is_church_admin(church_id, auth.uid()));

drop policy if exists "plan_progresses_select_access" on public.plan_progresses;
drop policy if exists "plan_progresses_update_self" on public.plan_progresses;
create policy "plan_progresses_select_access"
  on public.plan_progresses
  for select
  using (
    auth.uid() = user_id
    or exists (
      select 1
      from public.plans plan
      where plan.id = plan_progresses.plan_id
        and plan.church_id is not null
        and public.is_church_member(plan.church_id, auth.uid())
    )
  );
create policy "plan_progresses_update_self"
  on public.plan_progresses
  for update
  using (
    auth.uid() = user_id
    and public.is_plan_target_member(plan_id, auth.uid())
  )
  with check (
    auth.uid() = user_id
    and public.is_plan_target_member(plan_id, auth.uid())
  );

drop policy if exists "church_prayers_select_access" on public.church_prayers;
drop policy if exists "church_prayers_insert_access" on public.church_prayers;
drop policy if exists "church_prayers_update_manage" on public.church_prayers;
drop policy if exists "church_prayers_delete_manage" on public.church_prayers;
create policy "church_prayers_select_access"
  on public.church_prayers
  for select
  using (public.can_access_church_audience(church_id, team_id, auth.uid()));
create policy "church_prayers_insert_access"
  on public.church_prayers
  for insert
  with check (
    created_by_user_id = auth.uid()
    and public.can_access_church_audience(church_id, team_id, auth.uid())
  );
create policy "church_prayers_update_manage"
  on public.church_prayers
  for update
  using (public.can_manage_church_prayer(id, auth.uid()))
  with check (
    public.can_manage_church_prayer(id, auth.uid())
    and public.can_access_church_audience(church_id, team_id, auth.uid())
  );
create policy "church_prayers_delete_manage"
  on public.church_prayers
  for delete
  using (public.can_manage_church_prayer(id, auth.uid()));

drop policy if exists "church_prayer_contents_select_access" on public.church_prayer_contents;
drop policy if exists "church_prayer_contents_insert_access" on public.church_prayer_contents;
drop policy if exists "church_prayer_contents_update_manage" on public.church_prayer_contents;
drop policy if exists "church_prayer_contents_delete_manage" on public.church_prayer_contents;
create policy "church_prayer_contents_select_access"
  on public.church_prayer_contents
  for select
  using (public.can_access_church_prayer(prayer_id, auth.uid()));
create policy "church_prayer_contents_insert_access"
  on public.church_prayer_contents
  for insert
  with check (
    created_by_user_id = auth.uid()
    and public.can_access_church_prayer(prayer_id, auth.uid())
  );
create policy "church_prayer_contents_update_manage"
  on public.church_prayer_contents
  for update
  using (public.can_manage_church_prayer_content(id, auth.uid()))
  with check (public.can_manage_church_prayer_content(id, auth.uid()));
create policy "church_prayer_contents_delete_manage"
  on public.church_prayer_contents
  for delete
  using (public.can_manage_church_prayer_content(id, auth.uid()));

drop policy if exists "prayers_owner" on public.prayers;
create policy "prayers_owner"
  on public.prayers
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "prayer_contents_owner" on public.prayer_contents;
create policy "prayer_contents_owner"
  on public.prayer_contents
  for all
  using (
    exists (
      select 1
      from public.prayers
      where prayers.id = prayer_contents.prayer_id
        and prayers.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.prayers
      where prayers.id = prayer_contents.prayer_id
        and prayers.user_id = auth.uid()
    )
  );

drop policy if exists "bible_grass_owner" on public.bible_grass;
create policy "bible_grass_owner"
  on public.bible_grass
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "theme_verses_owner" on public.theme_verses;
create policy "theme_verses_owner"
  on public.theme_verses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "developer_inquiries_insert_public" on public.developer_inquiries;
create policy "developer_inquiries_insert_public"
  on public.developer_inquiries
  for insert
  with check (
    auth.role() in ('anon', 'authenticated')
    and (author_user_id is null or author_user_id = auth.uid())
  );

drop policy if exists "image_infos_owner" on public.image_infos;
create policy "image_infos_owner"
  on public.image_infos
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Community member metadata (202609080001)
begin;

-- metadata:tables
create schema if not exists church_metadata_private;
create table if not exists public.church_member_metadata_fields (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches(id) on delete cascade,
  system_key text,
  label text not null check (char_length(label) between 1 and 80 and label = btrim(label)),
  data_type text not null check (data_type in ('text', 'number', 'phone', 'binary', 'date', 'email')),
  options jsonb,
  is_active boolean not null default true,
  is_copyable boolean not null default false,
  edit_policy text not null default 'self_and_admins'
    check (edit_policy in ('super_admin_only', 'admins_only', 'self_and_admins', 'all_members')),
  sort_order integer not null default 0,
  version integer not null default 1 check (version > 0),
  created_by_user_id uuid references auth.users(id) on delete set null,
  updated_by_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (church_id, system_key),
  check (case when data_type = 'binary' then
    options is not null and jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 2
    else options is null end)
);

create table if not exists public.church_member_metadata (
  church_id bigint not null,
  user_id uuid not null,
  "values" jsonb not null default '{}'::jsonb check (jsonb_typeof("values") = 'object'),
  version integer not null default 1 check (version > 0),
  updated_by_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (church_id, user_id),
  foreign key (church_id, user_id) references public.church_memberships(church_id, user_id) on delete cascade
);

-- metadata:indexes
create unique index if not exists church_metadata_field_label_idx
  on public.church_member_metadata_fields(church_id, lower(btrim(label)));
create index if not exists church_metadata_field_order_idx
  on public.church_member_metadata_fields(church_id, is_active, sort_order, id);

-- metadata:helpers
create or replace function church_metadata_private._metadata_can_read(p_role text, p_actor uuid, p_target uuid, p_policy text)
returns boolean language sql immutable set search_path = '' as $$
  select coalesce(p_role in ('super_admin', 'deputy_admin') or p_actor = p_target
    or (p_role = 'member' and p_policy = 'all_members'), false);
$$;

create or replace function church_metadata_private._metadata_can_edit(p_role text, p_actor uuid, p_target uuid, p_policy text)
returns boolean language sql immutable set search_path = '' as $$
  select coalesce(case p_policy
    when 'super_admin_only' then p_role = 'super_admin'
    when 'admins_only' then p_role in ('super_admin', 'deputy_admin')
    when 'self_and_admins' then p_role in ('super_admin', 'deputy_admin') or (p_role = 'member' and p_actor = p_target)
    when 'all_members' then p_role in ('super_admin', 'deputy_admin', 'member')
    else false end, false);
$$;

create or replace function church_metadata_private._metadata_field_json(p_field public.church_member_metadata_fields)
returns jsonb language sql stable set search_path = '' as $$
  select to_jsonb(p_field) || jsonb_build_object('id', p_field.id::text, 'church_id', p_field.church_id::text);
$$;

create or replace function church_metadata_private._metadata_validate_definition(p_type text, p_options jsonb)
returns void language plpgsql set search_path = '' as $$
begin
  if p_type is null or p_type not in ('text', 'number', 'phone', 'binary', 'date', 'email') then
    raise exception 'METADATA_INVALID_TYPE';
  end if;
  if p_type <> 'binary' then
    if p_options is not null then raise exception 'METADATA_INVALID_OPTIONS'; end if;
    return;
  end if;
  if p_options is null or jsonb_typeof(p_options) <> 'array' then raise exception 'METADATA_INVALID_OPTIONS'; end if;
  if jsonb_array_length(p_options) <> 2 then raise exception 'METADATA_INVALID_OPTIONS'; end if;
  for i in 0..1 loop
    if jsonb_typeof(p_options->i) <> 'object'
      or p_options->i->>'value' is distinct from 'option_' || (i + 1)::text
      or jsonb_typeof(p_options->i->'label') is distinct from 'string'
      or char_length(btrim(p_options->i->>'label')) not between 1 and 40
      or p_options->i->>'label' <> btrim(p_options->i->>'label') then
      raise exception 'METADATA_INVALID_OPTIONS';
    end if;
  end loop;
  if lower(p_options->0->>'label') = lower(p_options->1->>'label') then
    raise exception 'METADATA_INVALID_OPTIONS';
  end if;
end;
$$;

create or replace function church_metadata_private._metadata_validate_value(p_field public.church_member_metadata_fields, p_value jsonb)
returns jsonb language plpgsql set search_path = '' as $$
declare v_text text; v_date date;
begin
  if p_value is null or p_value = 'null'::jsonb then return 'null'::jsonb; end if;
  if p_field.data_type = 'number' then
    if jsonb_typeof(p_value) <> 'number' then raise exception 'METADATA_INVALID_NUMBER'; end if;
    if abs((p_value #>> '{}')::numeric) > 9007199254740991 then raise exception 'METADATA_INVALID_NUMBER'; end if;
    begin
      if (p_value #>> '{}')::numeric is distinct from ((p_value #>> '{}')::double precision)::text::numeric then
        raise exception 'METADATA_INVALID_NUMBER';
      end if;
    exception when numeric_value_out_of_range then raise exception 'METADATA_INVALID_NUMBER'; end;
    return p_value;
  end if;
  if jsonb_typeof(p_value) <> 'string' then raise exception 'METADATA_INVALID_VALUE'; end if;
  v_text := regexp_replace(p_value #>> '{}', '^\s+|\s+$', '', 'g');
  if v_text = '' then return 'null'::jsonb; end if;
  if char_length(v_text) > 1000 then raise exception 'METADATA_VALUE_TOO_LONG'; end if;
  case p_field.data_type
    when 'binary' then
      if not exists(select 1 from jsonb_array_elements(p_field.options) o where o->>'value' = v_text) then
        raise exception 'METADATA_INVALID_OPTIONS';
      end if;
    when 'phone' then
      if char_length(v_text) > 40 or v_text !~ '^[+0-9 ()-]+$' or v_text !~ '[0-9]' then
        raise exception 'METADATA_INVALID_PHONE';
      end if;
    when 'email' then
      if char_length(v_text) > 254 or v_text !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
        raise exception 'METADATA_INVALID_EMAIL';
      end if;
    when 'date' then
      if v_text !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' then raise exception 'METADATA_INVALID_DATE'; end if;
      begin v_date := v_text::date;
      exception when others then raise exception 'METADATA_INVALID_DATE'; end;
      if to_char(v_date, 'YYYY-MM-DD') <> v_text or (p_field.system_key = 'birth_date' and v_date > (now() at time zone 'Asia/Seoul')::date) then
        raise exception 'METADATA_INVALID_DATE';
      end if;
    else null;
  end case;
  return to_jsonb(v_text);
end;
$$;

-- A trigger also protects immutable field identity from privileged accidental updates.
create or replace function church_metadata_private._metadata_guard_field()
returns trigger language plpgsql set search_path = '' as $$
begin
  perform church_metadata_private._metadata_validate_definition(new.data_type, new.options);
  if tg_op = 'UPDATE' then
    if (new.id, new.church_id, new.system_key, new.data_type) is distinct from
       (old.id, old.church_id, old.system_key, old.data_type) then raise exception 'METADATA_IMMUTABLE_FIELD'; end if;
  end if;
  return new;
end;
$$;

-- metadata:sync
create or replace function church_metadata_private._seed_church_member_metadata_fields(p_church_id bigint, p_creator uuid default null)
returns void language sql security definer set search_path = '' as $$
  insert into public.church_member_metadata_fields
    (church_id, system_key, label, data_type, options, is_copyable, sort_order, created_by_user_id)
  values
    (p_church_id, 'birth_date', '생년월일', 'date', null, false, 0, p_creator),
    (p_church_id, 'email', '이메일', 'email', null, true, 1, p_creator),
    (p_church_id, 'gender', '성별', 'binary', '[{"value":"option_1","label":"남"},{"value":"option_2","label":"여"}]', false, 2, p_creator),
    (p_church_id, 'phone', '연락처', 'phone', null, true, 3, p_creator),
    (p_church_id, 'address', '주소', 'text', null, true, 4, p_creator)
  on conflict (church_id, system_key) do nothing;
$$;

create or replace function church_metadata_private._metadata_on_church_created()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  perform church_metadata_private._seed_church_member_metadata_fields(new.id, new.created_by_user_id);
  return new;
end;
$$;

-- metadata:rpc
create or replace function church_metadata_private.get_church_member_metadata_fields(p_church_id bigint)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_fields jsonb;
begin
  select role into v_role from public.church_memberships where church_id = p_church_id and user_id = auth.uid();
  if v_role is null then raise exception 'PERMISSION_DENIED'; end if;
  select coalesce(jsonb_agg(church_metadata_private._metadata_field_json(f) order by sort_order, id), '[]'::jsonb)
    into v_fields from public.church_member_metadata_fields f where church_id = p_church_id;
  return jsonb_build_object('role', v_role, 'fields', v_fields);
end;
$$;

create or replace function church_metadata_private.create_church_member_metadata_field(
  p_church_id bigint, p_label text, p_data_type text, p_options jsonb,
  p_is_copyable boolean, p_edit_policy text default 'self_and_admins'
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_field public.church_member_metadata_fields;
begin
  -- Keep the parent alive without blocking membership cache updates on churches.
  perform 1 from public.churches where id = p_church_id for key share;
  perform pg_advisory_xact_lock(hashtextextended('church-metadata-fields:' || p_church_id::text, 0));
  select role into v_role from public.church_memberships where church_id = p_church_id and user_id = auth.uid() for share;
  if v_role is null or v_role not in ('super_admin', 'deputy_admin') then raise exception 'PERMISSION_DENIED'; end if;
  if v_role <> 'super_admin' and p_edit_policy is distinct from 'self_and_admins' then raise exception 'PERMISSION_DENIED'; end if;
  if p_label is null or char_length(btrim(p_label)) not between 1 and 80 then raise exception 'METADATA_INVALID_LABEL'; end if;
  if p_edit_policy is null or p_edit_policy not in ('super_admin_only', 'admins_only', 'self_and_admins', 'all_members') or p_is_copyable is null then
    raise exception 'METADATA_INVALID_SETTINGS';
  end if;
  if (select count(*) from public.church_member_metadata_fields where church_id = p_church_id) >= 100 then raise exception 'METADATA_FIELD_LIMIT'; end if;
  perform church_metadata_private._metadata_validate_definition(p_data_type, p_options);
  insert into public.church_member_metadata_fields
    (church_id, label, data_type, options, is_copyable, edit_policy, sort_order, created_by_user_id, updated_by_user_id)
  select p_church_id, btrim(p_label), p_data_type, p_options, p_is_copyable, p_edit_policy,
    coalesce(max(sort_order), -1) + 1, auth.uid(), auth.uid()
    from public.church_member_metadata_fields where church_id = p_church_id
  returning * into v_field;
  return church_metadata_private._metadata_field_json(v_field);
exception when unique_violation then raise exception 'METADATA_DUPLICATE_LABEL';
end;
$$;

create or replace function church_metadata_private.update_church_member_metadata_field(
  p_church_id bigint, p_field_id bigint, p_expected_version integer,
  p_label text, p_options jsonb, p_is_active boolean, p_is_copyable boolean, p_edit_policy text
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_field public.church_member_metadata_fields;
begin
  select role into v_role from public.church_memberships where church_id = p_church_id and user_id = auth.uid() for share;
  if v_role is null or v_role not in ('super_admin', 'deputy_admin') then raise exception 'PERMISSION_DENIED'; end if;
  select * into v_field from public.church_member_metadata_fields where church_id = p_church_id and id = p_field_id for update;
  if not found then raise exception 'METADATA_FIELD_NOT_FOUND'; end if;
  if v_field.version is distinct from p_expected_version then raise exception 'METADATA_CONFLICT'; end if;
  if v_role <> 'super_admin' and p_edit_policy is distinct from v_field.edit_policy then raise exception 'PERMISSION_DENIED'; end if;
  if p_label is null or char_length(btrim(p_label)) not between 1 and 80 then raise exception 'METADATA_INVALID_LABEL'; end if;
  if p_is_active is null or p_is_copyable is null or p_edit_policy is null or p_edit_policy not in ('super_admin_only', 'admins_only', 'self_and_admins', 'all_members') then
    raise exception 'METADATA_INVALID_SETTINGS';
  end if;
  perform church_metadata_private._metadata_validate_definition(v_field.data_type, p_options);
  update public.church_member_metadata_fields set label = btrim(p_label), options = p_options,
    is_active = p_is_active, is_copyable = p_is_copyable, edit_policy = p_edit_policy,
    version = version + 1, updated_by_user_id = auth.uid(), updated_at = now()
    where id = p_field_id returning * into v_field;
  return church_metadata_private._metadata_field_json(v_field);
exception when unique_violation then raise exception 'METADATA_DUPLICATE_LABEL';
end;
$$;

create or replace function church_metadata_private.get_church_member_metadata(p_church_id bigint, p_user_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_fields jsonb; v_values jsonb; v_version integer;
begin
  select role into v_role from public.church_memberships where church_id = p_church_id and user_id = auth.uid();
  if v_role is null or not public.is_church_member(p_church_id, p_user_id) then raise exception 'PERMISSION_DENIED'; end if;
  select "values", version into v_values, v_version from public.church_member_metadata where church_id = p_church_id and user_id = p_user_id;
  select coalesce(jsonb_agg(church_metadata_private._metadata_field_json(f) || jsonb_build_object(
      'can_edit', f.is_active and church_metadata_private._metadata_can_edit(v_role, auth.uid(), p_user_id, f.edit_policy),
      'value', coalesce(v_values->f.id::text, 'null'::jsonb)) order by f.sort_order, f.id), '[]'::jsonb)
    into v_fields from public.church_member_metadata_fields f where f.church_id = p_church_id
      and church_metadata_private._metadata_can_read(v_role, auth.uid(), p_user_id, f.edit_policy);
  return jsonb_build_object('fields', v_fields, 'version', coalesce(v_version, 0), 'role', v_role);
end;
$$;

create or replace function church_metadata_private.save_church_member_metadata(
  p_church_id bigint, p_user_id uuid, p_expected_version integer, p_field_versions jsonb, p_patch jsonb
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_field public.church_member_metadata_fields; v_key text; v_input jsonb; v_value jsonb;
  v_values jsonb; v_version integer;
begin
  if p_patch is null or jsonb_typeof(p_patch) <> 'object' or octet_length(p_patch::text) > 262144
    or p_field_versions is null or jsonb_typeof(p_field_versions) <> 'object' then raise exception 'METADATA_INVALID_VALUE'; end if;
  -- Lock both memberships in UUID order, including the missing metadata-row case.
  perform 1 from public.church_memberships where church_id = p_church_id and user_id in (auth.uid(), p_user_id) order by user_id for update;
  select role into v_role from public.church_memberships where church_id = p_church_id and user_id = auth.uid();
  if v_role is null or not public.is_church_member(p_church_id, p_user_id) then raise exception 'PERMISSION_DENIED'; end if;
  select "values", version into v_values, v_version from public.church_member_metadata where church_id = p_church_id and user_id = p_user_id for update;
  v_values := coalesce(v_values, '{}'::jsonb);
  if coalesce(v_version, 0) is distinct from p_expected_version then raise exception 'METADATA_CONFLICT'; end if;
  for v_key, v_input in select key, value from jsonb_each(p_patch) order by key loop
    select * into v_field from public.church_member_metadata_fields where church_id = p_church_id and id::text = v_key for share;
    if not found then raise exception 'METADATA_FIELD_NOT_FOUND'; end if;
    if not v_field.is_active then raise exception 'METADATA_FIELD_INACTIVE'; end if;
    if not church_metadata_private._metadata_can_edit(v_role, auth.uid(), p_user_id, v_field.edit_policy) then raise exception 'PERMISSION_DENIED'; end if;
    if p_field_versions->v_key is distinct from to_jsonb(v_field.version) then raise exception 'METADATA_CONFLICT'; end if;
    begin
      v_value := church_metadata_private._metadata_validate_value(v_field, v_input);
    exception when others then raise exception using message = sqlerrm, detail = v_key; end;
    if v_value = 'null'::jsonb then v_values := v_values - v_key;
    else v_values := jsonb_set(v_values, array[v_key], v_value); end if;
  end loop;
  if p_patch <> '{}'::jsonb then
    insert into public.church_member_metadata(church_id, user_id, "values", updated_by_user_id)
      values(p_church_id, p_user_id, v_values, auth.uid())
    on conflict (church_id, user_id) do update set "values" = excluded."values",
      version = church_member_metadata.version + 1, updated_by_user_id = auth.uid(), updated_at = now();
  end if;
  return church_metadata_private.get_church_member_metadata(p_church_id, p_user_id);
end;
$$;

create or replace function church_metadata_private.search_church_members_by_metadata(
  p_church_id bigint, p_field_id bigint, p_value jsonb, p_limit integer default 30, p_offset integer default 0
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_field public.church_member_metadata_fields; v_value jsonb; v_query text; v_result jsonb;
begin
  select role into v_role from public.church_memberships where church_id = p_church_id and user_id = auth.uid();
  if v_role is null then raise exception 'PERMISSION_DENIED'; end if;
  select * into v_field from public.church_member_metadata_fields where church_id = p_church_id and id = p_field_id;
  if not found then raise exception 'METADATA_FIELD_NOT_FOUND'; end if;
  if not v_field.is_active then raise exception 'METADATA_FIELD_INACTIVE'; end if;
  if p_limit is null or p_limit not between 1 and 100 or p_offset is null or p_offset < 0 then raise exception 'METADATA_INVALID_VALUE'; end if;
  if v_field.data_type in ('text', 'email', 'phone') then
    if p_value is null or jsonb_typeof(p_value) <> 'string' then raise exception 'METADATA_INVALID_VALUE'; end if;
    v_query := regexp_replace(p_value #>> '{}', '^\s+|\s+$', '', 'g');
    if char_length(v_query) not between 1 and 1000 then raise exception 'METADATA_INVALID_VALUE'; end if;
    if v_field.data_type = 'phone' then
      v_query := regexp_replace(v_query, '[^0-9]', '', 'g');
      if v_query = '' then raise exception 'METADATA_INVALID_PHONE'; end if;
    end if;
  else
    v_value := church_metadata_private._metadata_validate_value(v_field, p_value);
    if v_value = 'null'::jsonb then raise exception 'METADATA_INVALID_VALUE'; end if;
  end if;
  with matches as materialized (
    select m.user_id, m."values"->p_field_id::text as value,
      case ms.role when 'super_admin' then 0 when 'deputy_admin' then 1 else 2 end as role_order,
      coalesce(nullif(prof.display_name, ''), left(m.user_id::text, 8) || '...') as display_name,
      ms.role, team.name as team_name
    from public.church_member_metadata m
    join public.church_memberships ms on (ms.church_id, ms.user_id) = (m.church_id, m.user_id)
    left join public.user_profiles prof on prof.user_id = m.user_id
    left join public.teams team on team.id = ms.team_id and team.church_id = ms.church_id
    where m.church_id = p_church_id
      and church_metadata_private._metadata_can_read(v_role, auth.uid(), m.user_id, v_field.edit_policy)
      and m."values" ? p_field_id::text
      and case v_field.data_type
        when 'text' then strpos(lower(m."values"->>p_field_id::text), lower(v_query)) > 0
        when 'email' then strpos(lower(m."values"->>p_field_id::text), lower(v_query)) > 0
        when 'phone' then strpos(regexp_replace(m."values"->>p_field_id::text, '[^0-9]', '', 'g'), v_query) > 0
        else m."values"->p_field_id::text = v_value end
  ), page as (select * from matches order by role_order, display_name, user_id limit p_limit offset p_offset)
  select jsonb_build_object('total', (select count(*) from matches),
    'field', church_metadata_private._metadata_field_json(v_field),
    'items', coalesce((select jsonb_agg(jsonb_build_object('user_id', user_id, 'value', value, 'display_name', display_name, 'role', role, 'team_name', team_name) order by role_order, display_name, user_id) from page), '[]'::jsonb)) into v_result;
  return v_result;
end;
$$;

-- Public Data API entry points. Privileged implementations live outside exposed schemas.
create or replace function public.get_church_member_metadata_fields(p_church_id bigint)
returns jsonb language sql security invoker set search_path = '' as $$
  select church_metadata_private.get_church_member_metadata_fields(p_church_id);
$$;

create or replace function public.create_church_member_metadata_field(
  p_church_id bigint, p_label text, p_data_type text, p_options jsonb,
  p_is_copyable boolean, p_edit_policy text default 'self_and_admins'
)
returns jsonb language sql security invoker set search_path = '' as $$
  select church_metadata_private.create_church_member_metadata_field(p_church_id, p_label, p_data_type, p_options, p_is_copyable, p_edit_policy);
$$;

create or replace function public.update_church_member_metadata_field(
  p_church_id bigint, p_field_id bigint, p_expected_version integer,
  p_label text, p_options jsonb, p_is_active boolean, p_is_copyable boolean, p_edit_policy text
)
returns jsonb language sql security invoker set search_path = '' as $$
  select church_metadata_private.update_church_member_metadata_field(p_church_id, p_field_id, p_expected_version, p_label, p_options, p_is_active, p_is_copyable, p_edit_policy);
$$;

create or replace function public.get_church_member_metadata(p_church_id bigint, p_user_id uuid)
returns jsonb language sql security invoker set search_path = '' as $$
  select church_metadata_private.get_church_member_metadata(p_church_id, p_user_id);
$$;

create or replace function public.save_church_member_metadata(
  p_church_id bigint, p_user_id uuid, p_expected_version integer, p_field_versions jsonb, p_patch jsonb
)
returns jsonb language sql security invoker set search_path = '' as $$
  select church_metadata_private.save_church_member_metadata(p_church_id, p_user_id, p_expected_version, p_field_versions, p_patch);
$$;

create or replace function public.search_church_members_by_metadata(
  p_church_id bigint, p_field_id bigint, p_value jsonb, p_limit integer default 30, p_offset integer default 0
)
returns jsonb language sql security invoker set search_path = '' as $$
  select church_metadata_private.search_church_members_by_metadata(p_church_id, p_field_id, p_value, p_limit, p_offset);
$$;

-- metadata:triggers
drop trigger if exists church_metadata_field_guard on public.church_member_metadata_fields;
create trigger church_metadata_field_guard before insert or update on public.church_member_metadata_fields
  for each row execute function church_metadata_private._metadata_guard_field();
drop trigger if exists church_metadata_seed on public.churches;
create trigger church_metadata_seed after insert on public.churches
  for each row execute function church_metadata_private._metadata_on_church_created();

-- metadata:grants
revoke all on schema church_metadata_private from public, anon, authenticated;
grant usage on schema church_metadata_private to authenticated;
revoke all on public.church_member_metadata_fields, public.church_member_metadata from public, anon, authenticated;
grant select on public.church_member_metadata_fields, public.church_member_metadata to authenticated;
revoke all on sequence public.church_member_metadata_fields_id_seq from public, anon, authenticated;
do $$
declare f record;
begin
  for f in select oid::regprocedure as signature, proname from pg_proc where pronamespace in ('public'::regnamespace, 'church_metadata_private'::regnamespace)
    and proname in ('_metadata_can_read', '_metadata_can_edit', '_metadata_field_json', '_metadata_validate_definition',
      '_metadata_validate_value', '_metadata_guard_field', '_seed_church_member_metadata_fields', '_metadata_on_church_created',
      'get_church_member_metadata_fields', 'create_church_member_metadata_field', 'update_church_member_metadata_field',
      'get_church_member_metadata', 'save_church_member_metadata', 'search_church_members_by_metadata') loop
    execute format('revoke all on function %s from public, anon, authenticated', f.signature);
    if left(f.proname, 1) <> '_' then execute format('grant execute on function %s to authenticated', f.signature); end if;
  end loop;
end;
$$;

-- metadata:rls
alter table public.church_member_metadata_fields enable row level security;
alter table public.church_member_metadata enable row level security;
drop policy if exists church_metadata_fields_read on public.church_member_metadata_fields;
create policy church_metadata_fields_read on public.church_member_metadata_fields for select to authenticated
  using (public.is_church_member(church_id, (select auth.uid())));
drop policy if exists church_metadata_values_read on public.church_member_metadata;
create policy church_metadata_values_read on public.church_member_metadata for select to authenticated
  using (public.is_church_member(church_id, (select auth.uid())) and (user_id = (select auth.uid()) or public.is_church_admin(church_id, (select auth.uid()))));

-- metadata:backfill
select church_metadata_private._seed_church_member_metadata_fields(id) from public.churches;

commit;
