-- Fresh DB bootstrap
-- Kind: tables

begin;

create table if not exists public.bible_state (
  user_id uuid primary key references auth.users (id) on delete cascade,
  app_theme text not null default 'light',
  app_language text not null default 'ko',
  bible_search_info jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.favorite_verses (
  user_id uuid not null references auth.users (id) on delete cascade,
  book_code text not null,
  chapter integer not null,
  verse integer not null,
  verse_text text not null default '',
  created_at text not null default '',
  primary key (user_id, book_code, chapter, verse)
);

create table if not exists public.memos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  title text not null default '',
  content text not null default '',
  verse_text text not null default '',
  created_at text not null default ''
);

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null default '',
  email text,
  show_email boolean not null default false,
  avatar_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.churches (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  created_by_user_id uuid not null references auth.users (id) on delete restrict,
  super_admin_user_id uuid not null references auth.users (id) on delete restrict,
  member_count integer not null default 0,
  deputy_admin_user_ids text not null default ''
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  created_by_user_id uuid not null references auth.users (id) on delete restrict,
  leader_user_id uuid references auth.users (id) on delete set null
);

create table if not exists public.church_memberships (
  church_id bigint not null references public.churches (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null default 'member',
  team_id bigint references public.teams (id) on delete set null,
  joined_at timestamptz not null default timezone('utc', now()),
  created_by_user_id uuid references auth.users (id) on delete set null,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (church_id, user_id),
  constraint church_memberships_role_check check (role in ('super_admin', 'deputy_admin', 'member'))
);

create table if not exists public.church_join_requests (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches (id) on delete cascade,
  requester_user_id uuid not null references auth.users (id) on delete cascade,
  status text not null default 'pending',
  requested_at timestamptz not null default timezone('utc', now()),
  processed_at timestamptz,
  processed_by_user_id uuid references auth.users (id) on delete set null,
  constraint church_join_requests_status_check check (
    status in ('pending', 'approved', 'rejected', 'cancelled')
  )
);

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  plan_name text not null default '',
  start_date text not null default '',
  end_date text not null default '',
  total_read_count integer not null default 0,
  current_read_count integer not null default 0,
  goal_percent double precision not null default 0,
  read_count_per_day double precision not null default 0,
  rest_day integer not null default 0,
  goal_status jsonb not null default '[]'::jsonb,
  selected_book_codes jsonb not null default '[]'::jsonb,
  created_at text not null default '',
  updated_at text not null default '',
  church_id bigint references public.churches (id) on delete cascade,
  team_id bigint references public.teams (id) on delete cascade
);

create table if not exists public.memo_verses (
  user_id uuid not null references auth.users (id) on delete cascade,
  memo_id bigint not null references public.memos (id) on delete cascade,
  book_code text not null,
  chapter integer not null,
  verse integer not null,
  primary key (user_id, memo_id, book_code, chapter, verse)
);

create table if not exists public.plan_progresses (
  plan_id bigint not null references public.plans (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  goal_status jsonb not null default '[]'::jsonb,
  current_read_count integer not null default 0,
  goal_percent double precision not null default 0,
  read_count_per_day double precision not null default 0,
  rest_day integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (plan_id, user_id)
);

create table if not exists public.church_prayers (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches (id) on delete cascade,
  team_id bigint references public.teams (id) on delete cascade,
  requester text not null default '',
  target text not null default '',
  created_by_user_id uuid not null references auth.users (id) on delete cascade,
  created_at text not null default '',
  updated_at text not null default ''
);

create table if not exists public.church_prayer_contents (
  id bigint generated by default as identity primary key,
  prayer_id bigint not null references public.church_prayers (id) on delete cascade,
  created_by_user_id uuid not null references auth.users (id) on delete cascade,
  content text not null default '',
  registered_at text not null default ''
);

create table if not exists public.prayers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  requester text not null default '',
  target text not null default '',
  created_at text not null default ''
);

create table if not exists public.prayer_contents (
  id bigint generated by default as identity primary key,
  prayer_id bigint not null references public.prayers (id) on delete cascade,
  client_id text,
  content text not null default '',
  registered_at text not null default ''
);

create table if not exists public.bible_grass (
  user_id uuid not null references auth.users (id) on delete cascade,
  date text not null,
  data jsonb not null default '[]'::jsonb,
  primary key (user_id, date)
);

create table if not exists public.developer_inquiries (
  id bigint generated by default as identity primary key,
  author_user_id uuid references auth.users (id) on delete set null,
  author_name text not null default '',
  title text not null default '',
  content text not null default '',
  answer_content text not null default '',
  status text not null default 'inquiry',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint developer_inquiries_status_check check (status in ('inquiry', 'answered'))
);

commit;
