begin;

-- metadata:tables
create schema if not exists church_metadata_private;
create table if not exists public.church_member_metadata_fields (
  id bigint generated by default as identity primary key,
  church_id bigint not null references public.churches(id) on delete cascade,
  system_key text,
  label text not null check (char_length(label) between 1 and 80 and label = btrim(label)),
  data_type text not null check (data_type in ('text', 'number', 'phone', 'binary', 'date', 'email')),
  options jsonb,
  is_active boolean not null default true,
  is_copyable boolean not null default false,
  edit_policy text not null default 'self_and_admins'
    check (edit_policy in ('super_admin_only', 'admins_only', 'self_and_admins', 'all_members')),
  sort_order integer not null default 0,
  version integer not null default 1 check (version > 0),
  created_by_user_id uuid references auth.users(id) on delete set null,
  updated_by_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (church_id, system_key),
  check (case when data_type = 'binary' then
    options is not null and jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 2
    else options is null end)
);

create table if not exists public.church_member_metadata (
  church_id bigint not null,
  user_id uuid not null,
  "values" jsonb not null default '{}'::jsonb check (jsonb_typeof("values") = 'object'),
  version integer not null default 1 check (version > 0),
  updated_by_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (church_id, user_id),
  foreign key (church_id, user_id) references public.church_memberships(church_id, user_id) on delete cascade
);

-- metadata:indexes
create unique index if not exists church_metadata_field_label_idx
  on public.church_member_metadata_fields(church_id, lower(btrim(label)));
create index if not exists church_metadata_field_order_idx
  on public.church_member_metadata_fields(church_id, is_active, sort_order, id);

-- metadata:helpers
create or replace function church_metadata_private._metadata_can_read(p_role text, p_actor uuid, p_target uuid, p_policy text)
returns boolean language sql immutable set search_path = '' as $$
  select coalesce(p_role in ('super_admin', 'deputy_admin') or p_actor = p_target
    or (p_role = 'member' and p_policy = 'all_members'), false);
$$;

create or replace function church_metadata_private._metadata_can_edit(p_role text, p_actor uuid, p_target uuid, p_policy text)
returns boolean language sql immutable set search_path = '' as $$
  select coalesce(case p_policy
    when 'super_admin_only' then p_role = 'super_admin'
    when 'admins_only' then p_role in ('super_admin', 'deputy_admin')
    when 'self_and_admins' then p_role in ('super_admin', 'deputy_admin') or (p_role = 'member' and p_actor = p_target)
    when 'all_members' then p_role in ('super_admin', 'deputy_admin', 'member')
    else false end, false);
$$;

create or replace function church_metadata_private._metadata_field_json(p_field public.church_member_metadata_fields)
returns jsonb language sql stable set search_path = '' as $$
  select to_jsonb(p_field) || jsonb_build_object('id', p_field.id::text, 'church_id', p_field.church_id::text);
$$;

create or replace function church_metadata_private._metadata_validate_definition(p_type text, p_options jsonb)
returns void language plpgsql set search_path = '' as $$
begin
  if p_type is null or p_type not in ('text', 'number', 'phone', 'binary', 'date', 'email') then
    raise exception 'METADATA_INVALID_TYPE';
  end if;
  if p_type <> 'binary' then
    if p_options is not null then raise exception 'METADATA_INVALID_OPTIONS'; end if;
    return;
  end if;
  if p_options is null or jsonb_typeof(p_options) <> 'array' then raise exception 'METADATA_INVALID_OPTIONS'; end if;
  if jsonb_array_length(p_options) <> 2 then raise exception 'METADATA_INVALID_OPTIONS'; end if;
  for i in 0..1 loop
    if jsonb_typeof(p_options->i) <> 'object'
      or p_options->i->>'value' is distinct from 'option_' || (i + 1)::text
      or jsonb_typeof(p_options->i->'label') is distinct from 'string'
      or char_length(btrim(p_options->i->>'label')) not between 1 and 40
      or p_options->i->>'label' <> btrim(p_options->i->>'label') then
      raise exception 'METADATA_INVALID_OPTIONS';
    end if;
  end loop;
  if lower(p_options->0->>'label') = lower(p_options->1->>'label') then
    raise exception 'METADATA_INVALID_OPTIONS';
  end if;
end;
$$;

create or replace function church_metadata_private._metadata_validate_value(p_field public.church_member_metadata_fields, p_value jsonb)
returns jsonb language plpgsql set search_path = '' as $$
declare v_text text; v_date date;
begin
  if p_value is null or p_value = 'null'::jsonb then return 'null'::jsonb; end if;
  if p_field.data_type = 'number' then
    if jsonb_typeof(p_value) <> 'number' then raise exception 'METADATA_INVALID_NUMBER'; end if;
    if abs((p_value #>> '{}')::numeric) > 9007199254740991 then raise exception 'METADATA_INVALID_NUMBER'; end if;
    begin
      if (p_value #>> '{}')::numeric is distinct from ((p_value #>> '{}')::double precision)::text::numeric then
        raise exception 'METADATA_INVALID_NUMBER';
      end if;
    exception when numeric_value_out_of_range then raise exception 'METADATA_INVALID_NUMBER'; end;
    return p_value;
  end if;
  if jsonb_typeof(p_value) <> 'string' then raise exception 'METADATA_INVALID_VALUE'; end if;
  v_text := regexp_replace(p_value #>> '{}', '^\s+|\s+$', '', 'g');
  if v_text = '' then return 'null'::jsonb; end if;
  if char_length(v_text) > 1000 then raise exception 'METADATA_VALUE_TOO_LONG'; end if;
  case p_field.data_type
    when 'binary' then
      if not exists(select 1 from jsonb_array_elements(p_field.options) o where o->>'value' = v_text) then
        raise exception 'METADATA_INVALID_OPTIONS';
      end if;
    when 'phone' then
      if char_length(v_text) > 40 or v_text !~ '^[+0-9 ()-]+$' or v_text !~ '[0-9]' then
        raise exception 'METADATA_INVALID_PHONE';
      end if;
    when 'email' then
      if char_length(v_text) > 254 or v_text !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
        raise exception 'METADATA_INVALID_EMAIL';
      end if;
    when 'date' then
      if v_text !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' then raise exception 'METADATA_INVALID_DATE'; end if;
      begin v_date := v_text::date;
      exception when others then raise exception 'METADATA_INVALID_DATE'; end;
      if to_char(v_date, 'YYYY-MM-DD') <> v_text or (p_field.system_key = 'birth_date' and v_date > (now() at time zone 'Asia/Seoul')::date) then
        raise exception 'METADATA_INVALID_DATE';
      end if;
    else null;
  end case;
  return to_jsonb(v_text);
end;
$$;

-- A trigger also protects immutable field identity from privileged accidental updates.
create or replace function church_metadata_private._metadata_guard_field()
returns trigger language plpgsql set search_path = '' as $$
begin
  perform church_metadata_private._metadata_validate_definition(new.data_type, new.options);
  if tg_op = 'UPDATE' then
    if (new.id, new.church_id, new.system_key, new.data_type) is distinct from
       (old.id, old.church_id, old.system_key, old.data_type) then raise exception 'METADATA_IMMUTABLE_FIELD'; end if;
  end if;
  return new;
end;
$$;

-- metadata:sync
create or replace function church_metadata_private._seed_church_member_metadata_fields(p_church_id bigint, p_creator uuid default null)
returns void language sql security definer set search_path = '' as $$
  insert into public.church_member_metadata_fields
    (church_id, system_key, label, data_type, options, is_copyable, sort_order, created_by_user_id)
  values
    (p_church_id, 'birth_date', '생년월일', 'date', null, false, 0, p_creator),
    (p_church_id, 'email', '이메일', 'email', null, true, 1, p_creator),
    (p_church_id, 'gender', '성별', 'binary', '[{"value":"option_1","label":"남"},{"value":"option_2","label":"여"}]', false, 2, p_creator),
    (p_church_id, 'phone', '연락처', 'phone', null, true, 3, p_creator),
    (p_church_id, 'address', '주소', 'text', null, true, 4, p_creator)
  on conflict (church_id, system_key) do nothing;
$$;

create or replace function church_metadata_private._metadata_on_church_created()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  perform church_metadata_private._seed_church_member_metadata_fields(new.id, new.created_by_user_id);
  return new;
end;
$$;

-- metadata:rpc
create or replace function church_metadata_private.get_church_member_metadata_fields(p_church_id bigint)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_fields jsonb;
begin
  select role into v_role from public.church_memberships where church_id = p_church_id and user_id = auth.uid();
  if v_role is null then raise exception 'PERMISSION_DENIED'; end if;
  select coalesce(jsonb_agg(church_metadata_private._metadata_field_json(f) order by sort_order, id), '[]'::jsonb)
    into v_fields from public.church_member_metadata_fields f where church_id = p_church_id;
  return jsonb_build_object('role', v_role, 'fields', v_fields);
end;
$$;

create or replace function church_metadata_private.create_church_member_metadata_field(
  p_church_id bigint, p_label text, p_data_type text, p_options jsonb,
  p_is_copyable boolean, p_edit_policy text default 'self_and_admins'
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_field public.church_member_metadata_fields;
begin
  -- Keep the parent alive without blocking membership cache updates on churches.
  perform 1 from public.churches where id = p_church_id for key share;
  perform pg_advisory_xact_lock(hashtextextended('church-metadata-fields:' || p_church_id::text, 0));
  select role into v_role from public.church_memberships where church_id = p_church_id and user_id = auth.uid() for share;
  if v_role is null or v_role not in ('super_admin', 'deputy_admin') then raise exception 'PERMISSION_DENIED'; end if;
  if v_role <> 'super_admin' and p_edit_policy is distinct from 'self_and_admins' then raise exception 'PERMISSION_DENIED'; end if;
  if p_label is null or char_length(btrim(p_label)) not between 1 and 80 then raise exception 'METADATA_INVALID_LABEL'; end if;
  if p_edit_policy is null or p_edit_policy not in ('super_admin_only', 'admins_only', 'self_and_admins', 'all_members') or p_is_copyable is null then
    raise exception 'METADATA_INVALID_SETTINGS';
  end if;
  if (select count(*) from public.church_member_metadata_fields where church_id = p_church_id) >= 100 then raise exception 'METADATA_FIELD_LIMIT'; end if;
  perform church_metadata_private._metadata_validate_definition(p_data_type, p_options);
  insert into public.church_member_metadata_fields
    (church_id, label, data_type, options, is_copyable, edit_policy, sort_order, created_by_user_id, updated_by_user_id)
  select p_church_id, btrim(p_label), p_data_type, p_options, p_is_copyable, p_edit_policy,
    coalesce(max(sort_order), -1) + 1, auth.uid(), auth.uid()
    from public.church_member_metadata_fields where church_id = p_church_id
  returning * into v_field;
  return church_metadata_private._metadata_field_json(v_field);
exception when unique_violation then raise exception 'METADATA_DUPLICATE_LABEL';
end;
$$;

create or replace function church_metadata_private.update_church_member_metadata_field(
  p_church_id bigint, p_field_id bigint, p_expected_version integer,
  p_label text, p_options jsonb, p_is_active boolean, p_is_copyable boolean, p_edit_policy text
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_field public.church_member_metadata_fields;
begin
  select role into v_role from public.church_memberships where church_id = p_church_id and user_id = auth.uid() for share;
  if v_role is null or v_role not in ('super_admin', 'deputy_admin') then raise exception 'PERMISSION_DENIED'; end if;
  select * into v_field from public.church_member_metadata_fields where church_id = p_church_id and id = p_field_id for update;
  if not found then raise exception 'METADATA_FIELD_NOT_FOUND'; end if;
  if v_field.version is distinct from p_expected_version then raise exception 'METADATA_CONFLICT'; end if;
  if v_role <> 'super_admin' and p_edit_policy is distinct from v_field.edit_policy then raise exception 'PERMISSION_DENIED'; end if;
  if p_label is null or char_length(btrim(p_label)) not between 1 and 80 then raise exception 'METADATA_INVALID_LABEL'; end if;
  if p_is_active is null or p_is_copyable is null or p_edit_policy is null or p_edit_policy not in ('super_admin_only', 'admins_only', 'self_and_admins', 'all_members') then
    raise exception 'METADATA_INVALID_SETTINGS';
  end if;
  perform church_metadata_private._metadata_validate_definition(v_field.data_type, p_options);
  update public.church_member_metadata_fields set label = btrim(p_label), options = p_options,
    is_active = p_is_active, is_copyable = p_is_copyable, edit_policy = p_edit_policy,
    version = version + 1, updated_by_user_id = auth.uid(), updated_at = now()
    where id = p_field_id returning * into v_field;
  return church_metadata_private._metadata_field_json(v_field);
exception when unique_violation then raise exception 'METADATA_DUPLICATE_LABEL';
end;
$$;

create or replace function church_metadata_private.get_church_member_metadata(p_church_id bigint, p_user_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_fields jsonb; v_values jsonb; v_version integer;
begin
  select role into v_role from public.church_memberships where church_id = p_church_id and user_id = auth.uid();
  if v_role is null or not public.is_church_member(p_church_id, p_user_id) then raise exception 'PERMISSION_DENIED'; end if;
  select "values", version into v_values, v_version from public.church_member_metadata where church_id = p_church_id and user_id = p_user_id;
  select coalesce(jsonb_agg(church_metadata_private._metadata_field_json(f) || jsonb_build_object(
      'can_edit', f.is_active and church_metadata_private._metadata_can_edit(v_role, auth.uid(), p_user_id, f.edit_policy),
      'value', coalesce(v_values->f.id::text, 'null'::jsonb)) order by f.sort_order, f.id), '[]'::jsonb)
    into v_fields from public.church_member_metadata_fields f where f.church_id = p_church_id
      and church_metadata_private._metadata_can_read(v_role, auth.uid(), p_user_id, f.edit_policy);
  return jsonb_build_object('fields', v_fields, 'version', coalesce(v_version, 0), 'role', v_role);
end;
$$;

create or replace function church_metadata_private.save_church_member_metadata(
  p_church_id bigint, p_user_id uuid, p_expected_version integer, p_field_versions jsonb, p_patch jsonb
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_field public.church_member_metadata_fields; v_key text; v_input jsonb; v_value jsonb;
  v_values jsonb; v_version integer;
begin
  if p_patch is null or jsonb_typeof(p_patch) <> 'object' or octet_length(p_patch::text) > 262144
    or p_field_versions is null or jsonb_typeof(p_field_versions) <> 'object' then raise exception 'METADATA_INVALID_VALUE'; end if;
  -- Lock both memberships in UUID order, including the missing metadata-row case.
  perform 1 from public.church_memberships where church_id = p_church_id and user_id in (auth.uid(), p_user_id) order by user_id for update;
  select role into v_role from public.church_memberships where church_id = p_church_id and user_id = auth.uid();
  if v_role is null or not public.is_church_member(p_church_id, p_user_id) then raise exception 'PERMISSION_DENIED'; end if;
  select "values", version into v_values, v_version from public.church_member_metadata where church_id = p_church_id and user_id = p_user_id for update;
  v_values := coalesce(v_values, '{}'::jsonb);
  if coalesce(v_version, 0) is distinct from p_expected_version then raise exception 'METADATA_CONFLICT'; end if;
  for v_key, v_input in select key, value from jsonb_each(p_patch) order by key loop
    select * into v_field from public.church_member_metadata_fields where church_id = p_church_id and id::text = v_key for share;
    if not found then raise exception 'METADATA_FIELD_NOT_FOUND'; end if;
    if not v_field.is_active then raise exception 'METADATA_FIELD_INACTIVE'; end if;
    if not church_metadata_private._metadata_can_edit(v_role, auth.uid(), p_user_id, v_field.edit_policy) then raise exception 'PERMISSION_DENIED'; end if;
    if p_field_versions->v_key is distinct from to_jsonb(v_field.version) then raise exception 'METADATA_CONFLICT'; end if;
    begin
      v_value := church_metadata_private._metadata_validate_value(v_field, v_input);
    exception when others then raise exception using message = sqlerrm, detail = v_key; end;
    if v_value = 'null'::jsonb then v_values := v_values - v_key;
    else v_values := jsonb_set(v_values, array[v_key], v_value); end if;
  end loop;
  if p_patch <> '{}'::jsonb then
    insert into public.church_member_metadata(church_id, user_id, "values", updated_by_user_id)
      values(p_church_id, p_user_id, v_values, auth.uid())
    on conflict (church_id, user_id) do update set "values" = excluded."values",
      version = church_member_metadata.version + 1, updated_by_user_id = auth.uid(), updated_at = now();
  end if;
  return church_metadata_private.get_church_member_metadata(p_church_id, p_user_id);
end;
$$;

create or replace function church_metadata_private.search_church_members_by_metadata(
  p_church_id bigint, p_field_id bigint, p_value jsonb, p_limit integer default 30, p_offset integer default 0
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_field public.church_member_metadata_fields; v_value jsonb; v_query text; v_result jsonb;
begin
  select role into v_role from public.church_memberships where church_id = p_church_id and user_id = auth.uid();
  if v_role is null then raise exception 'PERMISSION_DENIED'; end if;
  select * into v_field from public.church_member_metadata_fields where church_id = p_church_id and id = p_field_id;
  if not found then raise exception 'METADATA_FIELD_NOT_FOUND'; end if;
  if not v_field.is_active then raise exception 'METADATA_FIELD_INACTIVE'; end if;
  if p_limit is null or p_limit not between 1 and 100 or p_offset is null or p_offset < 0 then raise exception 'METADATA_INVALID_VALUE'; end if;
  if v_field.data_type in ('text', 'email', 'phone') then
    if p_value is null or jsonb_typeof(p_value) <> 'string' then raise exception 'METADATA_INVALID_VALUE'; end if;
    v_query := regexp_replace(p_value #>> '{}', '^\s+|\s+$', '', 'g');
    if char_length(v_query) not between 1 and 1000 then raise exception 'METADATA_INVALID_VALUE'; end if;
    if v_field.data_type = 'phone' then
      v_query := regexp_replace(v_query, '[^0-9]', '', 'g');
      if v_query = '' then raise exception 'METADATA_INVALID_PHONE'; end if;
    end if;
  else
    v_value := church_metadata_private._metadata_validate_value(v_field, p_value);
    if v_value = 'null'::jsonb then raise exception 'METADATA_INVALID_VALUE'; end if;
  end if;
  with matches as materialized (
    select m.user_id, m."values"->p_field_id::text as value,
      case ms.role when 'super_admin' then 0 when 'deputy_admin' then 1 else 2 end as role_order,
      coalesce(nullif(prof.display_name, ''), left(m.user_id::text, 8) || '...') as display_name,
      ms.role, team.name as team_name
    from public.church_member_metadata m
    join public.church_memberships ms on (ms.church_id, ms.user_id) = (m.church_id, m.user_id)
    left join public.user_profiles prof on prof.user_id = m.user_id
    left join public.teams team on team.id = ms.team_id and team.church_id = ms.church_id
    where m.church_id = p_church_id
      and church_metadata_private._metadata_can_read(v_role, auth.uid(), m.user_id, v_field.edit_policy)
      and m."values" ? p_field_id::text
      and case v_field.data_type
        when 'text' then strpos(lower(m."values"->>p_field_id::text), lower(v_query)) > 0
        when 'email' then strpos(lower(m."values"->>p_field_id::text), lower(v_query)) > 0
        when 'phone' then strpos(regexp_replace(m."values"->>p_field_id::text, '[^0-9]', '', 'g'), v_query) > 0
        else m."values"->p_field_id::text = v_value end
  ), page as (select * from matches order by role_order, display_name, user_id limit p_limit offset p_offset)
  select jsonb_build_object('total', (select count(*) from matches),
    'field', church_metadata_private._metadata_field_json(v_field),
    'items', coalesce((select jsonb_agg(jsonb_build_object('user_id', user_id, 'value', value, 'display_name', display_name, 'role', role, 'team_name', team_name) order by role_order, display_name, user_id) from page), '[]'::jsonb)) into v_result;
  return v_result;
end;
$$;

-- Public Data API entry points. Privileged implementations live outside exposed schemas.
create or replace function public.get_church_member_metadata_fields(p_church_id bigint)
returns jsonb language sql security invoker set search_path = '' as $$
  select church_metadata_private.get_church_member_metadata_fields(p_church_id);
$$;

create or replace function public.create_church_member_metadata_field(
  p_church_id bigint, p_label text, p_data_type text, p_options jsonb,
  p_is_copyable boolean, p_edit_policy text default 'self_and_admins'
)
returns jsonb language sql security invoker set search_path = '' as $$
  select church_metadata_private.create_church_member_metadata_field(p_church_id, p_label, p_data_type, p_options, p_is_copyable, p_edit_policy);
$$;

create or replace function public.update_church_member_metadata_field(
  p_church_id bigint, p_field_id bigint, p_expected_version integer,
  p_label text, p_options jsonb, p_is_active boolean, p_is_copyable boolean, p_edit_policy text
)
returns jsonb language sql security invoker set search_path = '' as $$
  select church_metadata_private.update_church_member_metadata_field(p_church_id, p_field_id, p_expected_version, p_label, p_options, p_is_active, p_is_copyable, p_edit_policy);
$$;

create or replace function public.get_church_member_metadata(p_church_id bigint, p_user_id uuid)
returns jsonb language sql security invoker set search_path = '' as $$
  select church_metadata_private.get_church_member_metadata(p_church_id, p_user_id);
$$;

create or replace function public.save_church_member_metadata(
  p_church_id bigint, p_user_id uuid, p_expected_version integer, p_field_versions jsonb, p_patch jsonb
)
returns jsonb language sql security invoker set search_path = '' as $$
  select church_metadata_private.save_church_member_metadata(p_church_id, p_user_id, p_expected_version, p_field_versions, p_patch);
$$;

create or replace function public.search_church_members_by_metadata(
  p_church_id bigint, p_field_id bigint, p_value jsonb, p_limit integer default 30, p_offset integer default 0
)
returns jsonb language sql security invoker set search_path = '' as $$
  select church_metadata_private.search_church_members_by_metadata(p_church_id, p_field_id, p_value, p_limit, p_offset);
$$;

-- metadata:triggers
drop trigger if exists church_metadata_field_guard on public.church_member_metadata_fields;
create trigger church_metadata_field_guard before insert or update on public.church_member_metadata_fields
  for each row execute function church_metadata_private._metadata_guard_field();
drop trigger if exists church_metadata_seed on public.churches;
create trigger church_metadata_seed after insert on public.churches
  for each row execute function church_metadata_private._metadata_on_church_created();

-- metadata:grants
revoke all on schema church_metadata_private from public, anon, authenticated;
grant usage on schema church_metadata_private to authenticated;
revoke all on public.church_member_metadata_fields, public.church_member_metadata from public, anon, authenticated;
grant select on public.church_member_metadata_fields, public.church_member_metadata to authenticated;
revoke all on sequence public.church_member_metadata_fields_id_seq from public, anon, authenticated;
do $$
declare f record;
begin
  for f in select oid::regprocedure as signature, proname from pg_proc where pronamespace in ('public'::regnamespace, 'church_metadata_private'::regnamespace)
    and proname in ('_metadata_can_read', '_metadata_can_edit', '_metadata_field_json', '_metadata_validate_definition',
      '_metadata_validate_value', '_metadata_guard_field', '_seed_church_member_metadata_fields', '_metadata_on_church_created',
      'get_church_member_metadata_fields', 'create_church_member_metadata_field', 'update_church_member_metadata_field',
      'get_church_member_metadata', 'save_church_member_metadata', 'search_church_members_by_metadata') loop
    execute format('revoke all on function %s from public, anon, authenticated', f.signature);
    if left(f.proname, 1) <> '_' then execute format('grant execute on function %s to authenticated', f.signature); end if;
  end loop;
end;
$$;

-- metadata:rls
alter table public.church_member_metadata_fields enable row level security;
alter table public.church_member_metadata enable row level security;
drop policy if exists church_metadata_fields_read on public.church_member_metadata_fields;
create policy church_metadata_fields_read on public.church_member_metadata_fields for select to authenticated
  using (public.is_church_member(church_id, (select auth.uid())));
drop policy if exists church_metadata_values_read on public.church_member_metadata;
create policy church_metadata_values_read on public.church_member_metadata for select to authenticated
  using (public.is_church_member(church_id, (select auth.uid())) and (user_id = (select auth.uid()) or public.is_church_admin(church_id, (select auth.uid()))));

-- metadata:backfill
select church_metadata_private._seed_church_member_metadata_fields(id) from public.churches;

commit;
