create table if not exists public.theme_verses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  client_id text,
  year integer not null,
  book_code text not null default '',
  chapter integer not null default 1,
  verse integer not null default 1,
  verse_numbers jsonb not null default '[]'::jsonb,
  verse_text text not null default '',
  description text not null default '',
  created_at text not null default '',
  updated_at text not null default ''
);

alter table public.theme_verses
  add column if not exists verse_numbers jsonb not null default '[]'::jsonb;

update public.theme_verses
set verse_numbers = jsonb_build_array(greatest(1, verse))
where case
  when jsonb_typeof(verse_numbers) = 'array' then jsonb_array_length(verse_numbers)
  else 0
end = 0;

create unique index if not exists theme_verses_user_id_year_idx
  on public.theme_verses (user_id, year);

create unique index if not exists theme_verses_user_id_client_id_idx
  on public.theme_verses (user_id, client_id)
  where client_id is not null;

alter table public.theme_verses enable row level security;

drop policy if exists "theme_verses_owner" on public.theme_verses;
create policy "theme_verses_owner"
  on public.theme_verses
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
