begin;

alter table public.plans
  add column if not exists plan_description text not null default '';

create table if not exists public.bible_plan_template (
  id bigint generated by default as identity primary key,
  language_code text not null default 'ko',
  template_name text not null default '',
  template_explanation text not null default '',
  selected_book_codes jsonb not null default '[]'::jsonb
);

create index if not exists bible_plan_template_language_code_idx
  on public.bible_plan_template (language_code, id);

alter table public.bible_plan_template enable row level security;

drop policy if exists "bible_plan_template_read_public" on public.bible_plan_template;
create policy "bible_plan_template_read_public"
  on public.bible_plan_template
  for select
  using (true);

commit;
