create table if not exists public.developer_inquiries (
  id bigint generated by default as identity primary key,
  author_user_id uuid references auth.users (id) on delete set null,
  author_name text not null default '',
  title text not null default '',
  content text not null default '',
  answer_content text not null default '',
  status text not null default 'inquiry',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'developer_inquiries_status_check'
      and conrelid = 'public.developer_inquiries'::regclass
  ) then
    alter table public.developer_inquiries
      add constraint developer_inquiries_status_check
      check (status in ('inquiry', 'answered'));
  end if;
end;
$$;

create index if not exists developer_inquiries_status_created_at_idx
  on public.developer_inquiries (status, created_at desc, id desc);

create index if not exists developer_inquiries_author_user_id_created_at_idx
  on public.developer_inquiries (author_user_id, created_at desc, id desc);

drop trigger if exists developer_inquiries_set_updated_at on public.developer_inquiries;
create trigger developer_inquiries_set_updated_at
before update on public.developer_inquiries
for each row
execute function public.touch_updated_at();

alter table public.developer_inquiries enable row level security;

drop policy if exists "developer_inquiries_insert_public" on public.developer_inquiries;
create policy "developer_inquiries_insert_public"
  on public.developer_inquiries
  for insert
  with check (
    auth.role() in ('anon', 'authenticated')
    and (author_user_id is null or author_user_id = auth.uid())
  );
